updated the generate_dto.py for cleo's breaking changes
kodemore/opyapi pull request #6
Opened 2023-01-06 16:11 UTC by adamklifeworks

2023-01-06 16:35 UTC, Clokkehl requested changes
You need to update the version of opyapi on pyproject.toml to version 1.3.2, as this update would be a new package version. 

Also, poetry.lock has not been updated. So you should probably run `poetry update`

2023-01-06 16:36 UTC, adamklifeworks commented
> You need to update the version of opyapi on pyproject.toml to version 1.3.2, as this update would be a new package version.
> 
> Also, poetry.lock has not been updated. So you should probably run `poetry update`

Excellent well spotted thank you, will fix this now!

2023-02-01 13:51 UTC, Papipeto approved these changes

2023-02-01 13:52 UTC, Clokkehl approved these changes

2023-02-02 15:21 UTC, gezpage commented
Thanks for the fix @adamklifeworks ❤️

2023-02-02 15:21 UTC, merged